define(["viewmodels/exampleForm"], function (form) {
    var ctor = function () {
        this.canEdit = ko.observable(false);

        this.explicitFieldConfigsWithInvidualCanEdit = new form({
            text: {
                label: "My text label"
            },
            date: true,
            number: true,
            bool: true,
            textEdit: {
                canEdit: this.canEdit
            },
            numberEdit: {
                canEdit: this.canEdit
            },
            boolEdit: {
                canEdit: this.canEdit
            }
        });
        
        this.explicitFieldConfigsWithGlobalCanEdit = new form({
            canEdit: this.canEdit,
            fields: {
                text: true,
                date: true,
                number: true,
                bool: true,
                textEdit: true,
                numberEdit: true,
                boolEdit: true
            }
        });

        this.autoGeneratedOptions = new form();
        
        this.autoGeneratedOptionsWithCanEdit = new form({
            canEdit: this.canEdit
        });
        
        this.partiallyAutoGeneratedOptions = new form({
            autoGenerate: true,
            canEdit: this.canEdit,
            fields: {
                text: {
                    label: "Label overriden"
                }
            }
        });
    };
    
    return ctor;
});