using System;
using System.Web.Optimization;

namespace AutoGeneratedCrudForms {
  public class BundleConfig {
    public static void RegisterBundles(BundleCollection bundles) {
	  bundles.Add(
		new ScriptBundle("~/Scripts/vendor")
			.Include(
                "~/Scripts/jquery-{version}.js",
			    "~/Scripts/bootstrap.js",
			    "~/Scripts/knockout-{version}.js",
                "~/Scripts/knockout.binding-conventions-{version}.js",
                "~/Scripts/Globalize/globalize.js",
                "~/Scripts/knockout.validation.js",
                "~/Scripts/moment-{version}.js",
                "~/Scripts/bootstrap-datetimepicker.js")
		);

      bundles.Add(
        new StyleBundle("~/Content/css")
          .Include(
          "~/Content/bootstrap.css",
          "~/Content/site.css",
          "~/Content/bootstrap-datetimepicker.min.css")
          
        );
    }
  }
}